=== donatellosantoro/freESBee/freesbee-installer/updater-freESBee_2.0-console/build/classes/risorse/templateFolder/WEB-INF/classes/eccezioni/schema_eccezioni.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2008 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="rilevanza">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="posizione">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="eccezioni">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="eccezione" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="eccezione">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="codiceEccezione"/>
				<xs:element ref="contestoCodifica"/>
				<xs:element ref="posizione"/>
				<xs:element ref="rilevanza"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="contestoCodifica">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="codiceEccezione">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== donatellosantoro/freESBee/freesbee-installer/updater-freESBee_2.0-console/build/classes/risorse/templateFolder/WEB-INF/classes/eccezioni/eccezioni.xml
<?xml version="1.0" encoding="UTF-8"?>
<eccezioni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema_eccezioni.xsd">
	<eccezione>
		<codiceEccezione>001</codiceEccezione>
		<contestoCodifica>ErroreIntestazioneMessaggioSPCoop</contestoCodifica>
		<posizione>Mittente</posizione>
		<rilevanza>GRAVE</rilevanza>
	</eccezione>
	<eccezione>
		<codiceEccezione>100</codiceEccezione>
		<contestoCodifica>ErroreIntestazioneMessaggioSPCoop</contestoCodifica>
		<posizione>Mittente</posizione>
		<rilevanza>GRAVE</rilevanza>
	</eccezione>
	<eccezione>
		<codiceEccezione>101</codiceEccezione>
		<contestoCodifica>ErroreIntestazioneMessaggioSPCoop</contestoCodifica>
		<posizione>Mittente/IdentificativoParte</posizione>
		<rilevanza>GRAVE</rilevanza>
	</eccezione>
	<eccezione>
		<codiceEccezione>102</codiceEccezione>
		<contestoCodifica>ErroreIntestazioneMessaggioSPCoop</contestoCodifica>
		<posizione>Destinatario/IdentificativoParte</posizione>
		<rilevanza>GRAVE</rilevanza>
	</eccezione>
	<eccezione>
		<codiceEccezione>103</codiceEccezione>
		<contestoCodifica>ErroreIntestazioneMessaggioSPCoop</contestoCodifica>
		<posizione>ProfiloCollaborazione</posizione>
		<rilevanza>GRAVE</rilevanza>
	</eccezione>
	<eccezione>
		<codiceEccezione>104</codiceEccezione>
		<contestoCodifica>ErroreIntestazioneMessaggioSPCoop</contestoCodifica>
		<posizione>Collaborazione</posizione>
		<rilevanza>GRAVE</rilevanza>
	</eccezione>
	<eccezione>
		<codiceEccezione>105</codiceEccezione>
		<contestoCodifica>ErroreIntestazioneMessaggioSPCoop</contestoCodifica>
		<posizione>Servizio</posizione>
		<rilevanza>GRAVE</rilevanza>
	</eccezione>
	<eccezione>
		<codiceEccezione>106</codiceEccezione>
		<contestoCodifica>ErroreIntestazioneMessaggioSPCoop</contestoCodifica>
		<posizione>Azione</posizione>
		<rilevanza>GRAVE</rilevanza>
	</eccezione>
	<eccezione>
		<codiceEccezione>110</codiceEccezione>
		<contestoCodifica>ErroreIntestazioneMessaggioSPCoop</contestoCodifica>
		<posizione>Messaggio/Identificatore</posizione>
		<rilevanza>GRAVE</rilevanza>
	</eccezione>
	<eccezione>
		<codiceEccezione>300</codiceEccezione>
		<contestoCodifica>ErroreIntestazioneMessaggioSPCoop</contestoCodifica>
		<posizione>Corpo</posizione>
		<rilevanza>GRAVE</rilevanza>
	</eccezione>
</eccezioni>
